#!/usr/bin/env sh

PROJECT_PATH="$HOME/projects"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find $PROJECT_PATH \
        -mindepth 1 \
        -maxdepth 1 \
        -type d \
        | fzf --bind=ctrl-a:print-query)
fi

if [[ -z $selected ]]; then
    exit 0
fi

REPOSITORY_BASE_NAME=$(basename $selected)
NAME=$(echo $REPOSITORY_BASE_NAME | sed 's/\(.*\).git/\1/')
TARGET="$PROJECT_PATH/$NAME"

if [ ! -d $TARGET ]; then
    git clone $selected $TARGET
    selected=$TARGET
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi

exit 0

