source /usr/share/zsh/share/antigen.zsh

# experimental
# antigen bundle jeffreytse/zsh-vi-mode

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle joel-porquet/zsh-dircolors-solarized.git
antigen bundle chrissicool/zsh-256color

antigen use oh-my-zsh

# Load the theme.
antigen theme robbyrussell

antigen bundle autojump
antigen bundle git 
antigen bundle tmux
antigen bundle fzf 

antigen apply

# language environment setup
export LANG=en_US.UTF-8
export FZF_DEFAULT_OPTS='--height 80% --layout=reverse --border'
export EDITOR='nvim'

# print actual path as title 
case $TERM in
    xterm*|termite|alacritty|foot)
	precmd () {print -Pn "\e]0;[${PWD}]\a"}
        ;;
esac

# Personal setup (There i put all device specific configs, which are for
# example vivado license servers used at work ... these settings are excluded
# from the git repo)  
[[ ! -f ~/.personal_cfg.zsh ]] || source ~/.personal_cfg.zsh

# set vim mode
bindkey -v

# don't show user name@domain
prompt_context(){}

# USER SETTINGS
#
# Experimental
# function my_custom_widget() {
#     tmux_sessionizer
#     zle reset-prompt
# }

# function zvm_after_lazy_keybindings()
# {
#     zvm_define_widget my_custom_widget
#     bindkey -M vicmd '^F' my_custom_widget  
# }

# fuzzy find your projects and files
bindkey -s '^F' "tmux_sessionizer\n"

# GLOBAL VARIABLES FOR NNN
export NNN_PLUG='j:autojump;p:preview-tui;o:fzopen'
export NNN_FIFO="/tmp/nnn.fifo"

BLK="04" CHR="04" DIR="04" EXE="00" REG="00" HARDLINK="00" SYMLINK="06" MISSING="00" ORPHAN="01" FIFO="0F" SOCK="0F" OTHER="02"
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
